//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace DigiNG.Commands {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Recursos {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("DigiNG.Commands.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change_code_keeping_attributes.
        /// </summary>
        internal static string CambCodManteniendoAtributosName {
            get {
                return ResourceManager.GetString("CambCodManteniendoAtributosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change code while maintaining attributes.
        /// </summary>
        internal static string CambCodManteniendoAtributosTitle {
            get {
                return ResourceManager.GetString("CambCodManteniendoAtributosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy_database_attributes.
        /// </summary>
        internal static string CopiarAtributosBBDDName {
            get {
                return ResourceManager.GetString("CopiarAtributosBBDDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy database attributes.
        /// </summary>
        internal static string CopiarAtributosBBDDTitle {
            get {
                return ResourceManager.GetString("CopiarAtributosBBDDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy_code_name.
        /// </summary>
        internal static string CopiarNombreCódigoName {
            get {
                return ResourceManager.GetString("CopiarNombreCódigoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy code name maintaining attributes.
        /// </summary>
        internal static string CopiarNombreCódigoTitle {
            get {
                return ResourceManager.GetString("CopiarNombreCódigoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy_table_registr.
        /// </summary>
        internal static string CopiarTablaRegistroName {
            get {
                return ResourceManager.GetString("CopiarTablaRegistroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy code table/record keeping name.
        /// </summary>
        internal static string CopiarTablaRegistroTitle {
            get {
                return ResourceManager.GetString("CopiarTablaRegistroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut.
        /// </summary>
        internal static string CortarName {
            get {
                return ResourceManager.GetString("CortarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut_polygon.
        /// </summary>
        internal static string CortarPoligonoName {
            get {
                return ResourceManager.GetString("CortarPoligonoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut polygon.
        /// </summary>
        internal static string CortarPoligonoTitle {
            get {
                return ResourceManager.GetString("CortarPoligonoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CortarTitle {
            get {
                return ResourceManager.GetString("CortarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detect_lines_perimeter_lower.
        /// </summary>
        internal static string DetectaLíneasPerímetroInferiorAValorName {
            get {
                return ResourceManager.GetString("DetectaLíneasPerímetroInferiorAValorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detect_undershoot.
        /// </summary>
        internal static string DetectarUndershootName {
            get {
                return ResourceManager.GetString("DetectarUndershootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen an entity with more than one code. This order is not yet prepared for this scenario..
        /// </summary>
        internal static string HasSeleccionadoUnaEntidadConMasDeUnCodigoEstaOrdenNoEstaPreparada {
            get {
                return ResourceManager.GetString("HasSeleccionadoUnaEntidadConMasDeUnCodigoEstaOrdenNoEstaPreparada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and destination entities does not have common codes.
        /// </summary>
        internal static string LaEntidadOrigenYDestinoNoTienenCódigosComunes {
            get {
                return ResourceManager.GetString("LaEntidadOrigenYDestinoNoTienenCódigosComunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and destination entities have no common codes.
        /// </summary>
        internal static string LaEntidadQueHasSeleccionadoNoTieneNingúnEnlaceDeBaseDatos {
            get {
                return ResourceManager.GetString("LaEntidadQueHasSeleccionadoNoTieneNingúnEnlaceDeBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms lines to polygons. It is necessary to introduce codes of (closed) lines as parameters to transform into polygon. You can put multiple parameters and wildcards are also supported..
        /// </summary>
        internal static string LineaAPolígonoDescription {
            get {
                return ResourceManager.GetString("LineaAPolígonoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line_to_polygon.
        /// </summary>
        internal static string LineaAPolígonoName {
            get {
                return ResourceManager.GetString("LineaAPolígonoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line ({0}) with perimeter: {1} lower than {2}.
        /// </summary>
        internal static string LineaXConPerímetroYInferiorAZ {
            get {
                return ResourceManager.GetString("LineaXConPerímetroYInferiorAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located undershoot in line with code {0}.
        /// </summary>
        internal static string LocalizadoUndershootEnLaLíneaConCódigoX {
            get {
                return ResourceManager.GetString("LocalizadoUndershootEnLaLíneaConCódigoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The codes of the entities are different, so it cannot be joined.
        /// </summary>
        internal static string LosCódigosDeLasEntidadesSonDistintosYPoLoTantoNoSePuedenUnir {
            get {
                return ResourceManager.GetString("LosCódigosDeLasEntidadesSonDistintosYPoLoTantoNoSePuedenUnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude {0}.
        /// </summary>
        internal static string MagnitudX {
            get {
                return ResourceManager.GetString("MagnitudX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified the codes of the lines to convert to polygon.
        /// </summary>
        internal static string NoHaIndicadoLosCódigosDeLasLíneasAConvertirEnPolígono {
            get {
                return ResourceManager.GetString("NoHaIndicadoLosCódigosDeLasLíneasAConvertirEnPolígono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut_polygons.
        /// </summary>
        internal static string PartirPoligonosName {
            get {
                return ResourceManager.GetString("PartirPoligonosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut polygons.
        /// </summary>
        internal static string PartirPoligonosTitle {
            get {
                return ResourceManager.GetString("PartirPoligonosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trim_polygon.
        /// </summary>
        internal static string RecortarPoligonoName {
            get {
                return ResourceManager.GetString("RecortarPoligonoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trim_polygons.
        /// </summary>
        internal static string RecortarPoligonosName {
            get {
                return ResourceManager.GetString("RecortarPoligonosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim polygons.
        /// </summary>
        internal static string RecortarPoligonosTitle {
            get {
                return ResourceManager.GetString("RecortarPoligonosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim polygon.
        /// </summary>
        internal static string RecortarPoligonoTitle {
            get {
                return ResourceManager.GetString("RecortarPoligonoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the polygon to be cut.
        /// </summary>
        internal static string SeleccionaElPoligonoACortar {
            get {
                return ResourceManager.GetString("SeleccionaElPoligonoACortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the polygon to be trimmed.
        /// </summary>
        internal static string SeleccionaElPolígonoARecortar {
            get {
                return ResourceManager.GetString("SeleccionaElPolígonoARecortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the polygon to be joined.
        /// </summary>
        internal static string SeleccionaElPrimerPolígnoAUnir {
            get {
                return ResourceManager.GetString("SeleccionaElPrimerPolígnoAUnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the second polygon to join.
        /// </summary>
        internal static string SeleccionaElSegundoPolígonoAUnir {
            get {
                return ResourceManager.GetString("SeleccionaElSegundoPolígonoAUnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the destination entity....
        /// </summary>
        internal static string SeleccionaLaEntidadDestino {
            get {
                return ResourceManager.GetString("SeleccionaLaEntidadDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the origin entity....
        /// </summary>
        internal static string SeleccionaLaEntidadOrigen {
            get {
                return ResourceManager.GetString("SeleccionaLaEntidadOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the cutting line.
        /// </summary>
        internal static string SeleccionaLaLíneaDeCorte {
            get {
                return ResourceManager.GetString("SeleccionaLaLíneaDeCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the limit line.
        /// </summary>
        internal static string SeleccionaLaLíneaLímite {
            get {
                return ResourceManager.GetString("SeleccionaLaLíneaLímite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the line to cut.
        /// </summary>
        internal static string SeleccionaLíneaATramificar {
            get {
                return ResourceManager.GetString("SeleccionaLíneaATramificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entities was cutted and {1} entities was formed.
        /// </summary>
        internal static string SePartieronXEntidadesYSeFormaronYEntidadesNuevas {
            get {
                return ResourceManager.GetString("SePartieronXEntidadesYSeFormaronYEntidadesNuevas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert_vertex_selected_entity.
        /// </summary>
        internal static string TramificaInsertandoEntidadSeleccionadaName {
            get {
                return ResourceManager.GetString("TramificaInsertandoEntidadSeleccionadaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertices at the intersections of the selected line.
        /// </summary>
        internal static string TramificaInsertandoEntidadSeleccionadaTitle {
            get {
                return ResourceManager.GetString("TramificaInsertandoEntidadSeleccionadaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join_polygons.
        /// </summary>
        internal static string UnirPolígonosName {
            get {
                return ResourceManager.GetString("UnirPolígonosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join polygons.
        /// </summary>
        internal static string UnirPolígonosTitle {
            get {
                return ResourceManager.GetString("UnirPolígonosTitle", resourceCulture);
            }
        }
    }
}
